import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "./ui/components/sidenavi";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <div className="flex min-h-screen">
          <div className="w-64">
            <SideNav />
          </div>
          <div className="flex-1">
            <div className={inter.className}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
